### ISSUE TITLE
HDXmodeller

### ISSUE THREAD

**Issue by michbur** [hadexversum/HDX-MS-resources#5]
Add to the list: HDXmodeller: an online webserver for high-resolution HDX-MS with auto-validation.

**Comment by Jhsmit** [comment]
This one was added in #2, under High-resolution HDX-MS

**Comment by michbur** [comment]
Ah, missed it. thanks @Jhsmit!

**Comment by Jhsmit** [comment]
Its a bit tricky to spot it quickly because in that section we use author names (but not for PyHDX).
Maybe we should have both? Or update to a whole new format (table?)
